package application;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;

import db.DB;
import db.DbException;

public class ProgramDemoInserir {

	public static void main(String[] args) {
		
		SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
		Connection conn = null;
		//Statement QUE PERMITE ADICIONAR VÁRIOS COMANDOS SQL
		PreparedStatement st = null;
		
		try {
			conn = DB.openConnection();
			
			//INSERINDO DADOS NO BD
			/*
			 * prepareStatement(String sql, int autoGeneratedKeys):
			 * NO PRIMEIRO PARÂMETRO PODE SER PASSADO MAIS DE UMA INSERÇÃO
			 * NO SEGUNDO PARÂMETRO USA A FLAG "Statement" E CHAMA UM ENUMERADOR
			 */
			st = conn.prepareStatement(
					"INSERT INTO seller "
					+ "(Name, Email, BirthDate, BaseSalary, DepartmentId) "
					+ "VALUES "
					+ "(?, ?, ?, ?, ?)",
					Statement.RETURN_GENERATED_KEYS);
			//INSERINDO OS DADOS COM OS "set" DE ACORDO COM OS "VALUES"
			st.setString(1, "Noé");
			st.setString(2, "noe@gmail.com");
			st.setDate(3, new java.sql.Date(sdf.parse("23/11/1994").getTime()));
			st.setDouble(4, 3000.00);
			st.setInt(5, 4);
			
			//CERTIFICANDO E RETORNANDO A LINHAS ADICIONADAS
			//RETORNA UM INTEIRO DE QUANTAS LINHAS FORAM AFETADAS
			int rowsAffected = st.executeUpdate();
			
			if (rowsAffected > 0) {
				/*
				 * getGeneratedKeys() --> RETORNA UM ResultSet COM A CHAVE DO NOVO DADO INSERIDO
				 * O ResultSet É TIPO UMA FUNÇÃO QUE "PROJETA" TABELAS
				 */
				ResultSet rs = st.getGeneratedKeys();
				while(rs.next()) {
					//VAI PEGAR OS DADOS DA 1° COLUNA DA TABELA. POR MAIS QUE ESSA TABELA SÓ TENHA UMA COLUNA GERADA E UM CAMPO
					int id = rs.getInt(1);
					System.out.println("Done! Id = " + id);
				}
			} else {
					System.out.println("No rown affected!");
			}
		} catch (SQLException | ParseException e) {
			throw new DbException(e.getMessage());
		} finally {
			DB.closeStatement(st);
			DB.closeConnection();
		}

	}

}
